[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"
ar = "llvm-ar"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi21-clang"
ar = "llvm-ar"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.i686-linux-android]
linker = "i686-linux-android21-clang"
ar = "llvm-ar"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-linux-android]
linker = "x86_64-linux-android21-clang"
ar = "llvm-ar"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[env]
ANDROID_HOME = "/Users/bangle/Library/Android/sdk"
NDK_HOME = "/Users/bangle/Library/Android/sdk/ndk/29.0.13846066"
CC_aarch64-linux-android = "aarch64-linux-android21-clang"
CXX_aarch64-linux-android = "aarch64-linux-android21-clang++"
AR_aarch64-linux-android = "llvm-ar"
CC_armv7-linux-androideabi = "armv7a-linux-androideabi21-clang"
CXX_armv7-linux-androideabi = "armv7a-linux-androideabi21-clang++"
AR_armv7-linux-androideabi = "llvm-ar"
CC_i686-linux-android = "i686-linux-android21-clang"
CXX_i686-linux-android = "i686-linux-android21-clang++"
AR_i686-linux-android = "llvm-ar"
CC_x86_64-linux-android = "x86_64-linux-android21-clang"
CXX_x86_64-linux-android = "x86_64-linux-android21-clang++"
AR_x86_64-linux-android = "llvm-ar"
