version: '3.8'

# 核心应用服务
services:
  backend:
    container_name: joy-read-backend
    build:
      context: ../joy-read-service
      dockerfile: Dockerfile
    volumes:
      - ../joy-read-service:/app
      - /app/node_modules
    environment:
      - MEILISEARCH_HOST=http://meilisearch:7700
      - MEILISEARCH_API_KEY=SvuHwKxo38ozc0extjpI-Fi-uzYl5MmTYyDMfkwmolk
    command: npm start
    networks:
      - joy-read-net
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
      - meilisearch

  frontend:
    container_name: joy-read-frontend
    build:
      context: ../joy-read-web
      dockerfile: Dockerfile
    volumes:
      - ../joy-read-web:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost/api # API 地址指向 Nginx 网关
    command: npm run dev
    networks:
      - joy-read-net
    restart: unless-stopped
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: joy-read-nginx
    ports:
      - "80:80" # 应用的唯一入口
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # 挂载 nginx 配置
    depends_on:
      - backend
      - frontend
    networks:
      - joy-read-net
    restart: unless-stopped

networks:
  joy-read-net:
    driver: bridge
